---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: test-project
    app.kubernetes.io/name: test-project
    rht-gitops.com/janus-argocd: test-project
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: test-project
    app.kubernetes.io/name: test-project
    rht-gitops.com/janus-argocd: test-project
  name: storeuseradmin-sa
